#ifndef MESSAGEROUTINGTYPES_H
#define MESSAGEROUTINGTYPES_H

enum ACTION_TYPE {CREATE = 0, RETRIEVE, UPDATE, DELETE, INVALIDACTION};
enum DEST_TYPE   {ORDERING = 0, USER, CONTENT, COURSE, INVALIDDEST};

#endif // MESSAGEROUTINGTYPES_H
