#ifndef MESSAGEROUTINGTYPES_H
#define MESSAGEROUTINGTYPES_H

enum ACTION_TYPE {CREATE = 0, RETRIEVE, UPDATE, DELETE};
enum DEST_TYPE   {ORDERING = 0, USER, CONTENT, COURSE};

#endif // MESSAGEROUTINGTYPES_H
